version: "3.8"
services:
  pytorch-app:
    build:
      context: .
      dockerfile: Dockerfile
    # Use device_requests (Compose v3.8+) to request GPUs
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [ gpu ]
    env_file:
      - ../.env
    volumes:
      - ./data:/workspace/data # optional persistent data folder
    command: [ "bash" ]
