version: "3.8"
services:
  pytorch-app:
    container_name: ${PROJECT_NAME:-myTorch}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    env_file:
      - ../.env
    volumes:
      - ./data:/workspace/data
    command: [ "bash" ]