version: "3.8"
services:
  pytorch-app:
    build:
      context: .
      dockerfile: Dockerfile
    # Request GPU resources via deploy reservations (Compose v3.8)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    env_file:
      - ../.env
    volumes:
      - ./data:/workspace/data # optional persistent data folder
    command: [ "bash" ]
